<a href="https://colab.research.google.com/github/sripragnabitra/woc/blob/main/WOCLogReg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LOGISTIC REGRESSION**

**TRAINING MY MODEL**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/sripragnabitra/woc/main/classification_train.csv')
df

Unnamed: 0  label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  \
0             0      8       0       0       0       0       0       0   
1             1      4       0       0       0       0       0       0   
2             2      1       0       0       0       0       0       0   
3             3      8       0       0       0       0       0       0   
4             4      2       0       0       0       0       1       0   
..          ...    ...     ...     ...     ...     ...     ...     ...   
716         716      2       0       0       0       0       0       1   
717         717      2       0       0       0       0       0       0   
718         718      3       0       0       0       0       0       0   
719         719      3       0       0       0       0       0       0   
720         720      1       0       0       0       0       0       0   

     pixel7  pixel8  ...  pixel531  pixel532  pixel533  pixel534  pixel535  \
0         0       0  ...       229       100         0         0       131   
1         0       0  ...         0         0         0         0         0   
2         0       0  ...         0         0         0         0         0   
3         0       0  ...       181         0         0         0       234   
4         3       0  ...         0         0         0         0         0   
..      ...     ...  ...       ...       ...       ...       ...       ...   
716       5       0  ...         0         0         0         0         0   
717       0       0  ...         0         0         0         0         0   
718       0       0  ...         0         0         0         0         0   
719       0       0  ...         0         0         0         0         0   
720       0       0  ...         0         0         0         0         0   

     pixel536  pixel537  pixel538  pixel539  pixel540  
0         209       183       176       220       226  
1           0         0       123       236       205  
2           0         0         0         0         0  
3         247       222       224       221       219  
4           0       138       198       217       204  
..        ...       ...       ...       ...       ...  
716       143       193       206       228        59  
717         0        60        68       157        65  
718         0         0         0         0         0  
719         0         0         0         0         0  
720         0         0         0         0         0  

[721 rows x 542 columns]

In [ ]:
#for x_train, I took 0 to 199 index rows of pixel 60 to pixel 79 columns for logistic regression
x_train=df.iloc[:200,61:81]  
x_train=np.array(x_train)
print(x_train)
print('number of training features:', len(x_train))

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...  24   0   0]
 ...
 [  0   0   0 ... 122   0   2]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ... 110   0   0]]
number of training features: 200


In [ ]:
df1=pd.DataFrame(x_train, columns=['P1','P2','P3','P4','P5','P6','P7','P8','P9','P10','P11','P12','P13','P14','P15','P16','P17','P18','P19','P20'])
print(df1)

     P1   P2   P3   P4   P5   P6   P7   P8   P9  P10  P11  P12  P13  P14  P15  \
0     0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
1     0    0    0    0    0    0    0    0  126  222  218  214  209  214  223   
2     0    0    0    0   19  199  168   86  135  130  113  128   75  164  117   
3     0    0    0    0    0    4    0    0  217   86    0    0    0    0   11   
4     0    3    0    8  195  191  195  185  203  249  234  229  254  211  180   
..   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
195   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
196  30  221  168  166  157  200   12   60   83   41    8    4   24   80   62   
197   0    0    0    0    0    5    0  101  248  255  255  254  237  245  251   
198   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
199   0    0    0    0    5  112  196  255  231  237  200  123  234  227  232   

     P16  P17  P18  P19  P2

In [ ]:
#for y_train, I took 0 to 199 index rows of label column
y_train=df.iloc[0:200,1]
y_train=np.array(y_train) 
print(y_train)
print('number of training labels:', len(y_train))

[8 4 1 8 2 0 7 4 1 7 9 0 1 7 2 3 2 3 4 8 4 8 0 4 2 2 8 6 0 1 2 1 8 4 9 2 5
 4 2 2 2 0 6 9 1 9 5 0 2 4 2 2 4 7 8 6 9 4 1 0 0 6 7 7 7 9 7 8 5 1 7 9 3 7
 3 8 7 8 0 8 5 5 1 5 7 9 1 2 5 7 0 4 8 1 4 1 1 8 1 4 3 9 1 0 5 7 4 6 0 6 6
 0 1 7 4 8 5 7 0 8 3 9 1 7 7 6 7 5 3 7 8 2 8 2 5 1 9 8 7 6 1 7 1 0 7 3 6 5
 7 2 5 6 7 2 9 7 5 2 7 2 5 8 2 6 2 1 9 7 4 8 8 1 4 4 6 3 9 9 4 5 5 3 4 6 6
 8 1 2 7 0 3 1 7 2 1 5 6 0 5 0]
number of training labels: 200


In [ ]:
#creating dataframe
df1['Y']=y_train
df1

P1   P2   P3   P4   P5   P6   P7   P8   P9  P10  ...  P12  P13  P14  P15  \
0     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1     0    0    0    0    0    0    0    0  126  222  ...  214  209  214  223   
2     0    0    0    0   19  199  168   86  135  130  ...  128   75  164  117   
3     0    0    0    0    0    4    0    0  217   86  ...    0    0    0   11   
4     0    3    0    8  195  191  195  185  203  249  ...  229  254  211  180   
..   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
195   0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
196  30  221  168  166  157  200   12   60   83   41  ...    4   24   80   62   
197   0    0    0    0    0    5    0  101  248  255  ...  254  237  245  251   
198   0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
199   0    0    0    0    5  112  196  255  231  237  ...  123  234  227  232   

     P16  P17  P18  P19  P20  Y  
0      0    0    0    0    0  8  
1    149    0    0    0    0  4  
2    110  168   24    0    0  1  
3    204   71    0    7    0  8  
4    192  191  167    0    0  2  
..   ...  ...  ...  ...  ... ..  
195    0    0    0    0    0  5  
196   41  190  144  157  170  6  
197  234  255  122    0    2  0  
198    0    0    0    0    0  5  
199  255  220  110    0    0  0  

[200 rows x 21 columns]

In [ ]:
alpha = 0.01
num_iters = 1000

# Initialize coefficients to zero
coeffs = np.zeros(x_train.shape[1])

# Define sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Perform gradient descent
for i in range(num_iters):
    # Calculate predicted values
    y_pred = sigmoid(np.dot(x_train, coeffs))
    
    # Calculate errors
    errors = y_pred - y_train
    
    # Calculate gradients
    gradients = np.dot(x_train.T, errors) / len(y_train)
    
    # Update coefficients
    coeffs -= alpha * gradients

# Print the coefficients
print("Coefficients: ", coeffs)

Coefficients:  [   9.101        51.467675    147.500175    213.036025    318.896275
  638.23795     896.95475    1258.1501     1639.542175   1767.555
 1727.30120003 1934.887725   2114.47715    2085.78095    1825.65125
 1693.977125   1301.610675    913.4372      709.10629553  603.348275  ]


**TESTING MY MODEL**

In [ ]:
df2=pd.read_csv('https://raw.githubusercontent.com/sripragnabitra/woc/main/classification_test.csv')
df2

ids  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0     25672       0       0       0       0       0       0       0       9   
1     59964       0       0       0       0       0       0       0       0   
2     66230       0       0       0       0       0       0      14      53   
3     50801       0       0       0       0       0       0       0       0   
4     83307       0       0       0       0       0       0       0       0   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995  71009       0       0       0       0       0       0       0       0   
9996  67472       0       0       0       0       0       0       0       0   
9997  99226       0       0       0       0       0       0       0       0   
9998  58519       0       1       3       0       0       0       0       0   
9999  80458       0       0       0       0       0       0       0     140   

      pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0          8  ...       103        87        56         0         0         0   
1          0  ...        34         0         0         0         0         0   
2         99  ...         0         0         0         0        63        53   
3          0  ...       137       126       140         0       133       224   
4          0  ...         0         0         0         0         0         0   
...      ...  ...       ...       ...       ...       ...       ...       ...   
9995       0  ...        32        23        14        20         0         0   
9996       0  ...         0         0         0         2        52        23   
9997       0  ...       175       172       172       182       199       222   
9998       0  ...         0         0         0         0         0         1   
9999     119  ...       111        95        75        44         1         0   

      pixel781  pixel782  pixel783  pixel784  
0            0         0         0         0  
1            0         0         0         0  
2           31         0         0         0  
3          222        56         0         0  
4            0         0         0         0  
...        ...       ...       ...       ...  
9995         1         0         0         0  
9996        28         0         0         0  
9997        42         0         1         0  
9998         0         0         0         0  
9999         0         0         0         0  

[10000 rows x 785 columns]

In [ ]:
#for x_test, I took 0 to 199 index rows of pixel 60 to pixel 79 columns for logistic regression
x_test=df2.iloc[:200,61:81]  
x_test=np.array(x_test)
print(x_test)
print('number of training features:', len(x_test))

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0  70  58 ...  60  92   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0  43 ... 214  26   0]
 [  0   0   0 ... 220 183 154]]
number of training features: 200


In [ ]:
df3=pd.DataFrame(x_test, columns=['P1','P2','P3','P4','P5','P6','P7','P8','P9','P10','P11','P12','P13','P14','P15','P16','P17','P18','P19','P20'])
print(df3)

     P1  P2   P3   P4   P5   P6   P7   P8   P9  P10  P11  P12  P13  P14  P15  \
0     0   0    0    3   46  174  249   67    0   94  210   61   14  212  157   
1     0   0    0    0    0    0  103  227  217  218  222  189  216  201  215   
2     0  70   58   58   68   68  101  114   72  189  233  184   82  254   55   
3     0  59  219  248  231  254   27    3  221  253  242   79  190  123  228   
4     0   0    0    0  195  246  219  234  245  239  244  246  236  226  236   
..   ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
195   0  72  157  161  144  132  124  152  174  184  194  185  141  126  134   
196   0   0  182  231  225  217  239  175  228  255  134  126  144  138  173   
197   0   0    0    6   50   78  116   60  135  151  148  170   50  122   94   
198   0   0   43  194  243  218  250  226  204  245  204  237   58  173  240   
199   0   0    0    0    0    0    0    0    2    0    0  176  194  196  192   

     P16  P17  P18  P19  P20  
0     37

In [ ]:
y_pred = sigmoid(np.dot(x_test, coeffs))

# Print the prediction
print("Prediction: ", y_pred)

Prediction:  [1.  1.  1.  1.  1.  1.  0.5 1.  1.  1.  1.  1.  1.  1.  0.5 0.5 1.  1.
 1.  1.  1.  1.  1.  1.  0.5 0.5 1.  1.  1.  1.  0.5 0.5 0.5 1.  1.  1.
 1.  0.5 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  0.5 1.  1.  1.  1.  1.  0.5 1.  1.  1.  1.  1.  1.  0.5 1.  0.5 1.
 1.  1.  1.  0.5 1.  1.  1.  1.  0.5 1.  1.  1.  1.  0.5 0.5 1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  0.5 0.5 1.  0.5 1.  1.  1.  1.  1.  1.  1.
 1.  0.5 0.5 0.5 1.  1.  0.5 0.5 1.  1.  0.5 1.  1.  0.5 1.  1.  0.5 1.
 0.5 0.5 1.  1.  1.  0.5 0.5 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 1.  0.5
 0.5 1.  1.  1.  1.  1.  0.5 1.  1.  1.  0.5 1.  1.  1.  1.  0.5 0.5 0.5
 0.5 1.  1.  0.5 1.  0.5 0.5 1.  1.  0.5 1.  0.5 1.  1.  1.  1.  1.  1.
 1.  1. ]
